/*
module "clixxapp" {
    source    = "./clixxapp"
    AWS_REGION = var.AWS_REGION
    PATH_TO_PRIVATE_KEY=var.PATH_TO_PRIVATE_KEY
    PATH_TO_PUBLIC_KEY=var.PATH_TO_PUBLIC_KEY
    RDS_PASSWORD=var.RDS_PASSWORD
    AMIS=var.AMIS
    DB_USERNAME=var.DB_USERNAME
    DB_PASSWORD=var.DB_PASSWORD
    DATABASE_NAME=var.DATABASE_NAME
    AWS_SECRET_KEY=var.AWS_SECRET_KEY
    AWS_ACCESS_KEY=var.AWS_ACCESS_KEY
    AWS_RDS_ENDPOINT=var.AWS_RDS_ENDPOINT
    
}
*/


module "ec2" {
    source    = "./ec2"
    AWS_REGION = var.AWS_REGION
    PATH_TO_PRIVATE_KEY=var.PATH_TO_PRIVATE_KEY
    PATH_TO_PUBLIC_KEY=var.PATH_TO_PUBLIC_KEY
    RDS_PASSWORD=var.RDS_PASSWORD
    AMIS=var.AMIS
    DB_USERNAME=var.DB_USERNAME
    DB_PASSWORD=var.DB_PASSWORD
    DATABASE_NAME=var.DATABASE_NAME
    AWS_SECRET_KEY=var.AWS_SECRET_KEY
    AWS_ACCESS_KEY=var.AWS_ACCESS_KEY
    AWS_RDS_ENDPOINT=var.AWS_RDS_ENDPOINT
    
}


/*
module "ebs" {
    source    = "./ebs"
    AWS_REGION = var.AWS_REGION
    PATH_TO_PRIVATE_KEY=var.PATH_TO_PRIVATE_KEY
    PATH_TO_PUBLIC_KEY=var.PATH_TO_PUBLIC_KEY
    RDS_PASSWORD=var.RDS_PASSWORD
    AMIS=var.AMIS
    DB_USERNAME=var.DB_USERNAME
    DB_PASSWORD=var.DB_PASSWORD
    DATABASE_NAME=var.DATABASE_NAME
    AWS_SECRET_KEY=var.AWS_SECRET_KEY
    AWS_ACCESS_KEY=var.AWS_ACCESS_KEY
    AWS_RDS_ENDPOINT=var.AWS_RDS_ENDPOINT
    
}
*/